/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.CustomerController;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Asus
 */
public class CustomerRegistration extends javax.swing.JFrame {
    /*
     * Creates new form CustomerRegistation
     */
    private CustomerController customerController;
    private Connection conn;
    private PreparedStatement pst;
    private ResultSet rs;
    CustomerController controller = new CustomerController(this);
    


    public CustomerRegistration() {
        initComponents();
        //CustomerController controller = new CustomerController(this);
        controller.loadCustomerData();
        controller.autoIncrementRegistrationID();
        customerController = new CustomerController();
         
    }
    
    public void search() {
    String srch = searchbox.getText();
    
    try {
        String sql = "SELECT * FROM customers WHERE customerName LIKE '%" + srch + "%' OR registrationID LIKE '%" + srch + "%'";
        Connection conn = customerController.getConnections();
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        customertable.setModel(DbUtils.resultSetToTableModel(rs));
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}
    private void attachEventHandlers() {
        backBtn.addActionListener(evt -> backBtnActionPerformed(evt));
        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            search();
        }
    });
    }
    

    public String getCustomerName() {
        return cusName.getText();
        //return searchbox.getText();
    }

    public String getCustomerID() {
        return cusID.getText();
    }

    public String getLicence() {
        return licence.getText();
    }

    public String getTel() {
        return tel.getText();
    }

    public String getAddress() {
        return address.getText();
    }

    public String getRegistrationID() {
        return regiID.getText();
    }

    public void setRegistrationID(String id) {
        regiID.setText(id);
    }

    public JTable getCustomerTable() {
        return customertable;
    }

    public DefaultTableModel getCustomerTableModel() {
        return (DefaultTableModel) customertable.getModel();
    }

    public void clearField() {
        cusName.setText("");
        cusID.setText("");
        licence.setText("");
        tel.setText("");
        address.setText("");
        controller.autoIncrementRegistrationID();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustomerRegistation = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        customerName = new javax.swing.JLabel();
        IDCard = new javax.swing.JLabel();
        Licence = new javax.swing.JLabel();
        searchbox = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        cusID = new javax.swing.JTextField();
        licence = new javax.swing.JTextField();
        telephone = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        customertable = new javax.swing.JTable();
        cusaddress1 = new javax.swing.JLabel();
        customerName1 = new javax.swing.JLabel();
        regiID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        cusaddress2 = new javax.swing.JLabel();
        cusName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CustomerRegistation.setBackground(new java.awt.Color(139, 177, 229));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("Customer Registation");

        backBtn.setBackground(new java.awt.Color(153, 255, 255));
        backBtn.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(153, 255, 204));
        addBtn.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        customerName.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        customerName.setForeground(new java.awt.Color(0, 0, 153));
        customerName.setText("Registation ID");

        IDCard.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        IDCard.setForeground(new java.awt.Color(0, 0, 153));
        IDCard.setText("ID card No.");

        Licence.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Licence.setForeground(new java.awt.Color(0, 0, 153));
        Licence.setText("Driving Licence No.");

        searchbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchboxActionPerformed(evt);
            }
        });

        tel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        cusID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        licence.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        telephone.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        telephone.setForeground(new java.awt.Color(0, 0, 153));
        telephone.setText("Telephone No.");

        address.setColumns(20);
        address.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        customertable.setBackground(new java.awt.Color(204, 255, 204));
        customertable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        customertable.setForeground(new java.awt.Color(70, 60, 5));
        customertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registation ID", "Customer Name", "ID No", "Licence No", "Telephone", "Address"
            }
        ));
        customertable.setSelectionBackground(new java.awt.Color(153, 153, 255));
        customertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customertableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(customertable);

        cusaddress1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cusaddress1.setForeground(new java.awt.Color(0, 0, 153));
        cusaddress1.setText("Search by Registration ID or Customer Name:");

        customerName1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        customerName1.setForeground(new java.awt.Color(0, 0, 153));
        customerName1.setText("Customer name");

        regiID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        regiID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regiIDActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fox car_resized (1).jpg"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        resetBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        cusaddress2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cusaddress2.setForeground(new java.awt.Color(0, 0, 153));
        cusaddress2.setText("Address");

        cusName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CustomerRegistationLayout = new javax.swing.GroupLayout(CustomerRegistation);
        CustomerRegistation.setLayout(CustomerRegistationLayout);
        CustomerRegistationLayout.setHorizontalGroup(
            CustomerRegistationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerRegistationLayout.createSequentialGroup()
                .addGroup(CustomerRegistationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomerRegistationLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(CustomerRegistationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CustomerRegistationLayout.createSequentialGroup()
                                .addGroup(CustomerRegistationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(customerName1)
                                    .addComponent(customerName))
                                .addGap(40, 40, 40)
                                .addGroup(CustomerRegistationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cusName)
                                    .addComponent(regiID, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CustomerRegistationLayout.createSequentialGroup()
                                .addComponent(IDCard)
                                .addGap(76, 76, 76)
                                .addComponent(cusID, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CustomerRegistationLayout.createSequentialGroup()
                                .addComponent(Licence)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(licence, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CustomerRegistationLayout.createSequentialGroup()
                                .addComponent(telephone)
                                .addGap(50, 50, 50)
                                .addGroup(CustomerRegistationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(tel)))
                            .addComponent(cusaddress2)
                            .addGroup(CustomerRegistationLayout.createSequentialGroup()
                                .addComponent(addBtn)
                                .addGap(38, 38, 38)
                                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CustomerRegistationLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(CustomerRegistationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerRegistationLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cusaddress1)
                        .addGap(18, 18, 18)
                        .addComponent(searchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(CustomerRegistationLayout.createSequentialGroup()
                        .addGroup(CustomerRegistationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(CustomerRegistationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CustomerRegistationLayout.setVerticalGroup(
            CustomerRegistationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerRegistationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerRegistationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerRegistationLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(CustomerRegistationLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CustomerRegistationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regiID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CustomerRegistationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cusName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerName1))
                        .addGap(16, 16, 16)
                        .addGroup(CustomerRegistationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cusID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDCard))
                        .addGap(18, 18, 18)
                        .addGroup(CustomerRegistationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Licence)
                            .addComponent(licence, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(CustomerRegistationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telephone))
                        .addGap(15, 15, 15)
                        .addGroup(CustomerRegistationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cusaddress2))
                        .addGap(51, 51, 51)
                        .addGroup(CustomerRegistationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBtn)
                            .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(CustomerRegistationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusaddress1)
                    .addComponent(searchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(backBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CustomerRegistation, javax.swing.GroupLayout.PREFERRED_SIZE, 1151, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CustomerRegistation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchboxActionPerformed
        search();
    }//GEN-LAST:event_searchboxActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
     
        Home home = new Home();
           this.hide();
          home.setVisible(true);
        
    }//GEN-LAST:event_backBtnActionPerformed

  
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        controller.addCustomer();
    }//GEN-LAST:event_addBtnActionPerformed

    
    private void customertableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customertableMouseClicked
        int selectedRow = customertable.getSelectedRow();
    DefaultTableModel model = (DefaultTableModel) customertable.getModel();
    int columnCount = model.getColumnCount();
    
    if (selectedRow != -1) {
        if (columnCount > 0) regiID.setText(model.getValueAt(selectedRow, 0).toString());
        if (columnCount > 1) cusName.setText(model.getValueAt(selectedRow, 1).toString());
        if (columnCount > 2) cusID.setText(model.getValueAt(selectedRow, 2).toString());
        if (columnCount > 3) licence.setText(model.getValueAt(selectedRow, 3).toString());
        if (columnCount > 4) tel.setText(model.getValueAt(selectedRow, 4).toString());
        if (columnCount > 5) address.setText(model.getValueAt(selectedRow, 5).toString());
    }
    }//GEN-LAST:event_customertableMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        controller.updateCustomer();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        controller.deleteCustomer();
    }//GEN-LAST:event_DeleteBtnActionPerformed
    
    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        clearField();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void regiIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regiIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regiIDActionPerformed

    private void cusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusNameActionPerformed
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CustomerRegistation;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JLabel IDCard;
    private javax.swing.JLabel Licence;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextArea address;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField cusID;
    private javax.swing.JTextField cusName;
    private javax.swing.JLabel cusaddress1;
    private javax.swing.JLabel cusaddress2;
    private javax.swing.JLabel customerName;
    private javax.swing.JLabel customerName1;
    private javax.swing.JTable customertable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField licence;
    private javax.swing.JTextField regiID;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTextField searchbox;
    private javax.swing.JTextField tel;
    private javax.swing.JLabel telephone;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

    
}
